version: '3'

services:
  api:
    build: ./api
    restart: on-failure


  web:
    build: ./sensorweb
    volumes:
      - ./sensorweb/:/api
    restart: on-failure
    
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - web

