version: '3'

services:
  api:
    build: ./api
    restart: on-failure
    volumes:
      - ./api/src:/api/src
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - STAGE=${STAGE}
      - MONGODB_URI=${MONGODB_URI}

  web:
    build: ./sensorweb
    restart: on-failure
    volumes:
      - ./sensorweb/src:/web/src
      - ./sensorweb/public:/web/public
      - ./sensorweb/locales:/web/locales
    environment:
      - STAGE=${STAGE}

  script:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile.script
    volumes:
      - ./scripts:/scripts
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - api
      - web
      

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - web

