version: '3'

services:
  api:
    build: ./api
    restart: on-failure

  web:
    build: ./web
    volumes:
      - ./web/:/api
    restart: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - web
