version: '3'

services:
  api:
    build: ./api
    restart: on-failure
    volumes:
    - ./api/src:/api/src


  web:
    build: ./sensorweb
    restart: on-failure
    volumes:
      - ./sensorweb/src:/web/src
    
    
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      
    ports:
      - "80:80"
    depends_on:
      - api
      - web

