name: Update Docker Compose and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Copy Docker Compose file to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLETPASS }}
          source: docker-compose.yml
          target: ~/docker-compose.yml

      - name: Connect to Droplet and update Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLETPASS }}
          script: |
            cd /root/SensorNet
            git pull
            docker-compose pull
            docker-compose up --build -d
          env:
            DB_CONNECTION: ${{secrets.db_connection}}
            STAGE: production
            
